### ISSUE TITLE
ERROR OCCUR

### ISSUE THREAD

**Issue by VLadImirluren** [zhenyuw16/Uni3DETR#6]
command: srun -p Ai4sci_3D --gres=gpu:1 bash extra_tools/dist_train.sh ./projects/configs/uni3detr/uni3detr_scannet.py 1

problem:
Traceback (most recent call last):
  File "/mnt/lustre/houyuenan/anaconda3/envs/unidetr/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/mnt/petrelfs/dengken_nerf_perception/DETR/Uni3DETR/mmdetection3d/projects/mmdet3d_plugin/models/detectors/uni3detr.py", line 128, in __init__
    super(Uni3DETR, self).__init__(pts_voxel_layer, pts_voxel_encoder,
  File "/mnt/petrelfs/dengken_nerf_perception/DETR/Uni3DETR/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 62, in __init__
    self.pts_bbox_head = builder.build_head(pts_bbox_head)
  File "/mnt/petrelfs/dengken_nerf_perception/DETR/Uni3DETR/mmdetection3d/mmdet3d/models/builder.py", line 68, in build_head
    return MMDET_HEADS.build(cfg)
  File "/mnt/lustre/houyuenan/anaconda3/envs/unidetr/lib/python3.8/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/mnt/lustre/houyuenan/anaconda3/envs/unidetr/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/mnt/lustre/houyuenan/anaconda3/envs/unidetr/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AssertionError: Uni3DETRHead: The classification weight for loss and matcher should beexactly the same.

pip list:
absl-py                 2.0.0
addict                  2.4.0
aliyun-python-sdk-core  2.14.0
aliyun-python-sdk-kms   2.16.2
black                   23.11.0
boto3                   1.28.80
botocore                1.31.80
cachetools              5.3.2
certifi                 2023.11.17
cffi                    1.16.0
charset-normalizer      3.3.2
click                   8.1.7
colorama                0.4.6
coloredlogs             15.0.1
contourpy               1.1.1
crcmod                  1.7
cryptography            41.0.5
cycler                  0.12.1
decorator               5.1.1
descartes               1.1.0
environs                9.5.0
exceptiongroup          1.2.0
fire                    0.5.0
flake8                  6.1.0
fonttools               4.45.1
google-auth             2.23.4
google-auth-oauthlib    1.1.0
grpcio                  1.60.0rc1
humanfriendly           10.0
humanize                4.8.0
idna                    3.6
imageio                 2.33.0
importlib-metadata      6.8.0
importlib-resources     6.1.1
iniconfig               2.0.0
jmespath                0.10.0
joblib                  1.3.2
kiwisolver              1.4.5
llvmlite                0.41.1
lyft-dataset-sdk        0.0.8
Markdown                3.5.1
markdown-it-py          3.0.0
MarkupSafe              2.1.3
marshmallow             3.20.1
matplotlib              3.5.3
mccabe                  0.7.0
mdurl                   0.1.2
mmcls                   1.0.0rc6
mmcv                    1.7.0
mmcv-full               1.6.0
mmdet                   2.28.0
mmdet3d                 1.0.0rc5                 /mnt/petrelfs/dengken_nerf_perception/DETR/Uni3DETR/mmdetection3d
mmengine                0.10.1
mmsegmentation          0.30.0
model-index             0.1.11
modelindex              0.0.2
multiprocessing-logging 0.3.4
mypy-extensions         1.0.0
networkx                2.2
numba                   0.58.1
numpy                   1.23.0
nuscenes-devkit         1.1.11
oauthlib                3.2.2
opencv-python           4.8.1.78
opendatalab             0.0.10
openmim                 0.3.9
openxlab                0.0.29
ordered-set             4.1.0
oss2                    2.17.0
packaging               23.2
pandas                  2.0.3
pathspec                0.11.2
petrel-oss-sdk          v2.2.1-2-g1505ef3-master
Pillow                  10.1.0
pip                     23.3.1
platformdirs            4.0.0
plotly                  5.18.0
pluggy                  1.3.0
plyfile                 1.0.2
prettytable             3.9.0
protobuf                4.23.4
pyasn1                  0.5.1
pyasn1-modules          0.3.0
pycocotools             2.0.7
pycodestyle             2.11.1
pycparser               2.21
pycryptodome            3.19.0
pyflakes                3.1.0
Pygments                2.17.2
pyparsing               3.1.1
pyquaternion            0.9.9
pytest                  7.4.3
python-dateutil         2.8.2
python-dotenv           1.0.0
pytz                    2023.3.post1
PyWavelets              1.4.1
PyYAML                  6.0.1
requests                2.28.2
requests-oauthlib       1.3.1
rich                    13.4.2
rsa                     4.9
scikit-image            0.15.0
scikit-learn            1.3.2
scipy                   1.10.1
setuptools              60.2.0
Shapely                 1.8.5.post1
six                     1.16.0
tabulate                0.9.0
tenacity                8.2.3
tensorboard             2.15.1
tensorboard-data-server 0.7.2
termcolor               2.3.0
terminaltables          3.1.10
threadpoolctl           3.2.0
tomli                   2.0.1
torch                   1.9.1+cu111
torchaudio              0.9.1
torchvision             0.10.1+cu111
tqdm                    4.65.2
trimesh                 2.35.39
typing_extensions       4.8.0
tzdata                  2023.3
urllib3                 1.26.18
wcwidth                 0.2.12
Werkzeug                3.0.1
wheel                   0.41.2
yapf                    0.40.1
zipp                    3.17.0

THANKS A LOT..........

**Comment by CBY-9527** [comment]
> command: srun -p Ai4sci_3D --gres=gpu:1 bash extra_tools/dist_train.sh ./projects/configs/uni3detr/uni3detr_scannet.py 1
> 
> problem: Traceback (most recent call last): File "/mnt/lustre/houyuenan/anaconda3/envs/unidetr/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg return obj_cls(**args) File "/mnt/petrelfs/dengken_nerf_perception/DETR/Uni3DETR/mmdetection3d/projects/mmdet3d_plugin/models/detectors/uni3detr.py", line 128, in **init** super(Uni3DETR, self).**init**(pts_voxel_layer, pts_voxel_encoder, File "/mnt/petrelfs/dengken_nerf_perception/DETR/Uni3DETR/mmdetection3d/mmdet3d/models/detectors/mvx_two_stage.py", line 62, in **init** self.pts_bbox_head = builder.build_head(pts_bbox_head) File "/mnt/petrelfs/dengken_nerf_perception/DETR/Uni3DETR/mmdetection3d/mmdet3d/models/builder.py", line 68, in build_head return MMDET_HEADS.build(cfg) File "/mnt/lustre/houyuenan/anaconda3/envs/unidetr/lib/python3.8/site-packages/mmcv/utils/registry.py", line 237, in build return self.build_func(*args, **kwargs, registry=self) File "/mnt/lustre/houyuenan/anaconda3/envs/unidetr/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg return build_from_cfg(cfg, registry, default_args) File "/mnt/lustre/houyuenan/anaconda3/envs/unidetr/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg raise type(e)(f'{obj_cls.**name**}: {e}') AssertionError: Uni3DETRHead: The classification weight for loss and matcher should beexactly the same.
> 
> pip list: absl-py 2.0.0 addict 2.4.0 aliyun-python-sdk-core 2.14.0 aliyun-python-sdk-kms 2.16.2 black 23.11.0 boto3 1.28.80 botocore 1.31.80 cachetools 5.3.2 certifi 2023.11.17 cffi 1.16.0 charset-normalizer 3.3.2 click 8.1.7 colorama 0.4.6 coloredlogs 15.0.1 contourpy 1.1.1 crcmod 1.7 cryptography 41.0.5 cycler 0.12.1 decorator 5.1.1 descartes 1.1.0 environs 9.5.0 exceptiongroup 1.2.0 fire 0.5.0 flake8 6.1.0 fonttools 4.45.1 google-auth 2.23.4 google-auth-oauthlib 1.1.0 grpcio 1.60.0rc1 humanfriendly 10.0 humanize 4.8.0 idna 3.6 imageio 2.33.0 importlib-metadata 6.8.0 importlib-resources 6.1.1 iniconfig 2.0.0 jmespath 0.10.0 joblib 1.3.2 kiwisolver 1.4.5 llvmlite 0.41.1 lyft-dataset-sdk 0.0.8 Markdown 3.5.1 markdown-it-py 3.0.0 MarkupSafe 2.1.3 marshmallow 3.20.1 matplotlib 3.5.3 mccabe 0.7.0 mdurl 0.1.2 mmcls 1.0.0rc6 mmcv 1.7.0 mmcv-full 1.6.0 mmdet 2.28.0 mmdet3d 1.0.0rc5 /mnt/petrelfs/dengken_nerf_perception/DETR/Uni3DETR/mmdetection3d mmengine 0.10.1 mmsegmentation 0.30.0 model-index 0.1.11 modelindex 0.0.2 multiprocessing-logging 0.3.4 mypy-extensions 1.0.0 networkx 2.2 numba 0.58.1 numpy 1.23.0 nuscenes-devkit 1.1.11 oauthlib 3.2.2 opencv-python 4.8.1.78 opendatalab 0.0.10 openmim 0.3.9 openxlab 0.0.29 ordered-set 4.1.0 oss2 2.17.0 packaging 23.2 pandas 2.0.3 pathspec 0.11.2 petrel-oss-sdk v2.2.1-2-g1505ef3-master Pillow 10.1.0 pip 23.3.1 platformdirs 4.0.0 plotly 5.18.0 pluggy 1.3.0 plyfile 1.0.2 prettytable 3.9.0 protobuf 4.23.4 pyasn1 0.5.1 pyasn1-modules 0.3.0 pycocotools 2.0.7 pycodestyle 2.11.1 pycparser 2.21 pycryptodome 3.19.0 pyflakes 3.1.0 Pygments 2.17.2 pyparsing 3.1.1 pyquaternion 0.9.9 pytest 7.4.3 python-dateutil 2.8.2 python-dotenv 1.0.0 pytz 2023.3.post1 PyWavelets 1.4.1 PyYAML 6.0.1 requests 2.28.2 requests-oauthlib 1.3.1 rich 13.4.2 rsa 4.9 scikit-image 0.15.0 scikit-learn 1.3.2 scipy 1.10.1 setuptools 60.2.0 Shapely 1.8.5.post1 six 1.16.0 tabulate 0.9.0 tenacity 8.2.3 tensorboard 2.15.1 tensorboard-data-server 0.7.2 termcolor 2.3.0 terminaltables 3.1.10 threadpoolctl 3.2.0 tomli 2.0.1 torch 1.9.1+cu111 torchaudio 0.9.1 torchvision 0.10.1+cu111 tqdm 4.65.2 trimesh 2.35.39 typing_extensions 4.8.0 tzdata 2023.3 urllib3 1.26.18 wcwidth 0.2.12 Werkzeug 3.0.1 wheel 0.41.2 yapf 0.40.1 zipp 3.17.0
> 
> THANKS A LOT..........

Have you solved it? I have the same problem.

**Comment by CodeWZT** [comment]
actually，i have the same error, do you solve this issue?

**Comment by yzbx** [comment]
change the config file, align the loss_cls in Head with train_cfg.assigner.cls_cost

```
# from 
# loss_cls=dict(type='SoftFocalLoss', use_sigmoid=True, gamma=2.0, alpha=0.25, loss_weight=1.5),

# to
loss_cls=dict(type='SoftFocalLoss', use_sigmoid=True, gamma=2.0, alpha=0.25, loss_weight=2.0),
```
